Update CI-CD.yml

diff --git a/.github/workflows/CI-CD.yml b/.github/workflows/CI-CD.yml
--- a/.github/workflows/CI-CD.yml
+++ b/.github/workflows/CI-CD.yml
@@ -99,17 +99,17 @@ jobs:
       - name: Start app in background 🚀
         run: |
           node server.js &
-          sleep 2
+          sleep 5
 
       - name: Wait for app to be ready ⏱️
         run: |
-          for i in {1..15}; do
+          for i in {1..20}; do
             if curl -s http://localhost:4500/test >/dev/null 2>&1; then
               echo "✅ App is ready!"
               exit 0
             fi
             echo "⏳ Waiting for app..."
-            sleep 2
+            sleep 4
           done
           echo "❌ App failed to start"
           exit 1
@@ -117,30 +117,12 @@ jobs:
       - name: Initialize local DB 🚀
         run: |
           curl http://localhost:4500/initialize
-          sleep 1
+          sleep 5
 
           
       - name: Run login API tests 📝
         run: |
           localUrl="http://localhost:4500/login"
-
-
-          echo "** Test 2: Wrong login **"
-          response=$(curl -s -X POST $localUrl \
-          -H "Content-Type: application/json" \
-          -d '{"email": "wrong@gmail.com", "password": "Abc@12345"}')
-          if echo "$response" | jq empty 2>/dev/null; then
-            token=$(echo "$response" | jq -r ".token")
-            if [ "$token" != "null" ] && [ -n "$token" ]; then
-              echo "Fail: Wrong login have a token"
-              exit 1
-            else
-              echo "Ok: $(echo "$response" | jq -r '.message // "unexpected response"')"
-            fi
-          else
-            echo "Ok: $response"
-          fi
-
 
            echo "** Test 1: Correct login **"
           response=$(curl -s -X POST $localUrl \
@@ -163,6 +145,23 @@ jobs:
           else
             echo "Fail: $response"
             exit 1
+          fi
+
+
+          echo "** Test 2: Wrong login **"
+          response=$(curl -s -X POST $localUrl \
+          -H "Content-Type: application/json" \
+          -d '{"email": "wrong@gmail.com", "password": "Abc@12345"}')
+          if echo "$response" | jq empty 2>/dev/null; then
+            token=$(echo "$response" | jq -r ".token")
+            if [ "$token" != "null" ] && [ -n "$token" ]; then
+              echo "Fail: Wrong login have a token"
+              exit 1
+            else
+              echo "Ok: $(echo "$response" | jq -r '.message // "unexpected response"')"
+            fi
+          else
+            echo "Ok: $response"
           fi
 
           echo "** Test 3: Wrong Password **"
