Update CI-CD.yml

diff --git a/.github/workflows/CI-CD.yml b/.github/workflows/CI-CD.yml
--- a/.github/workflows/CI-CD.yml
+++ b/.github/workflows/CI-CD.yml
@@ -99,16 +99,19 @@ jobs:
             sleep 10
 
             for i in {1..10}; do
-            if docker logs test-backend 2>&1 | grep -q "Connected to Mongo"; then
-              echo "✅ Backend successfully connected to Mongo!"
-              exit 0
-            fi
-            echo "⏳ Waiting for backend to connect to Mongo..."
-            sleep 3
-          done
-          echo "❌ Backend failed to connect to Mongo"
-          docker logs test-backend
-          exit 1
+              if docker logs test-backend 2>&1 | grep -q "Connected to Mongo"; then
+                echo "✅ Backend successfully connected to Mongo!"
+                exit 0
+              fi
+              echo "⏳ Waiting for backend to connect to Mongo..."
+              sleep 3
+            done
+          
+            echo "❌ Backend failed to connect to Mongo"
+            docker logs test-backend
+            exit 1
+          fi
+          
             
 
 
