added api test on EKS

diff --git a/.github/workflows/CI-CD.yml b/.github/workflows/CI-CD.yml
--- a/.github/workflows/CI-CD.yml
+++ b/.github/workflows/CI-CD.yml
@@ -304,20 +304,79 @@ jobs:
             if [ -n "$P" ]; then kubectl logs -n ${EKS_NAMESPACE} "$P" --tail=200 || true; fi
 
 
-      - name: Wait for LoadBalancer to be ready ⏱️
+      - name: run login API test on EKS
         run: |
           echo "Checking if LoadBalancer is ready..."
           for i in {1..15}; do
             LB=$(kubectl get svc ${APP_NAME} -n ${EKS_NAMESPACE} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' || true)
             if [ -n "$LB" ]; then break; fi
-            echo "Waiting for LoadBalancer..."
-            sleep 10
+              echo "Waiting for LoadBalancer..."
+              sleep 10
           done
           if [ -z "$LB" ]; then
             echo "Fail: LoadBalancer hostname not available"
             exit 1
           fi
-         
+
+          echo "✅ LoadBalancer is ready"
+          API_URL="http://$LB/login"
+
+          echo "** Test 1: Correct login **"
+          response=$(curl -s -X POST "$API_URL" \
+          -H "Content-Type: application/json" \
+          -d "${{ secrets.MONGO_TEST_USER }}")
+          if echo "$response" | jq empty 2>/dev/null; then
+            token=$(echo "$response" | jq -r ".token")
+            if [ "$token" != "null" ] && [ -n "$token" ]; then
+              echo "Ok: User successfully logged-in"
+            else
+              error_msg=$(echo "$response" | jq -r '.message // empty')
+              if [ -n "$error_msg" ]; then
+                echo "Fail: $error_msg"
+                exit 1
+              else
+                echo "Fail: unexpected response"
+                exit 1
+              fi
+            fi
+          else
+            echo "Fail: $response"
+            exit 1
+          fi
+
+          echo "** Test 2: Wrong login **"
+          response=$(curl -s -X POST "$API_URL" \
+          -H "Content-Type: application/json" \
+          -d '{"email": "wrong@gmail.com", "password": "Abc@12345"}')
+          if echo "$response" | jq empty 2>/dev/null; then
+            token=$(echo "$response" | jq -r ".token")
+            if [ "$token" != "null" ] && [ -n "$token" ]; then
+              echo "Fail: Wrong login have a token"
+              exit 1
+            else
+              echo "Ok: $(echo "$response" | jq -r '.message // "unexpected response"')"
+            fi
+          else
+            echo "Ok: $response"
+          fi
+
+          echo "** Test 3: Wrong Password **"
+          response=$(curl -s -X POST "$API_URL" \
+          -H "Content-Type: application/json" \
+          -d '{"email": "nir@gmail.com", "password": "Abc@12345"}')
+          if echo "$response" | jq empty 2>/dev/null; then
+            token=$(echo "$response" | jq -r ".token")
+            if [ "$token" != "null" ] && [ -n "$token" ]; then
+              echo "Fail: Wrong password have a token"
+              exit 1
+            else
+              echo "Ok: $(echo "$response" | jq -r '.message // "unexpected response"')"
+            fi
+          else
+            echo "Ok: $response"
+          fi 
+
+     
 
       - name: Show service endpoint 🌐
         run: |
